version: '3.9'
services:
  web:
    build: .
    container_name: expense_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0 --port=5000
